@startuml
'https://plantuml.com/use-case-diagram
'!theme spacelab

'ein counter for Quotes checker einschalten, wenn der 2 wird speichern
'wenn der counter nie 2
[*] --> INIT
INIT --> QUOTE : "\""
INIT --> WORD : [a-zA-Z]
QUOTE --> WORD : [^a-zA-Z]
QUOTE --> QUOTE : "\""
WORD --> QUOTE : "\""
@endusl
