@startuml
'https://plantuml.com/use-case-diagram
'!theme spacelab
'
'QUOTE -> WORD -> QUOTE -> WORD #IST NO GO
'QUOTE -> , -> zählt nicht #IST NO GO
'"ok","ok, ok",ok"ok","nicht"ok,"nicht ok
'[*] --> INIT
'INIT --> QUOTE : "
'QUOTE --> WORD : [a-zA-Z]
'WORD --> QUOTE : "
'INIT --> WORD : [a-zA-Z]


[*] --> NOCELL

state CELL {
    CELL --> NOCELL : ,
    CELL --> CELL : *
}

state NOCELL {
    NOCELL --> CELL : *
    NOCELL --> STRINGCELL : "
    NOCELL --> NOCELL : ,
    NOCELL --> NOCELL : Whitespace
}

state STRINGCELL {
    STRINGCELL --> STRINGEND : "
    STRINGCELL --> STRINGCELL : *
    STRINGCELL --> EXEPTION : end
}

state STRINGEND {
    STRINGEND --> EXEPTION : *
    STRINGEND --> NOCELL : ,
    STRINGEND --> STRINGCELL : "
}

state EXEPTION {
}
@enduml